### ISSUE TITLE
能否自定义唤醒词？

### ISSUE THREAD

**Issue by zuowanbushiwo** [chenyangMl/keyword-spot#1]
你好
      感谢您开源这个项目，如果要定制唤醒词需要怎么做？我看 snowboy (https://snowboy.hahack.com/) 定制唤醒词比较简单。
谢谢！

**Comment by chenyangMl** [comment]
> 你好 感谢您开源这个项目，如果要定制唤醒词需要怎么做？我看 snowboy (https://snowboy.hahack.com/) 定制唤醒词比较简单。 谢谢！

定制唤醒词我目前看到的都是Finetune的方案，会出训练教程。您提到的这个感觉像是以前的特征匹配方案，不是很了解哈。

**Comment by shanhaidexiamo** [comment]
你好，有训练思路了么

**Comment by chenyangMl** [comment]
你收索一下kaldi2 ，实测不错。

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2025年06月20日 15:56 |
| 收件人 | chenyangMl/keyword-spot ***@***.***> |
| 抄送人 | Chen ***@***.***>,
State ***@***.***> |
| 主题 | Re: [chenyangMl/keyword-spot] 能否自定义唤醒词？ (Issue #1) |
shanhaidexiamo left a comment (chenyangMl/keyword-spot#1)

你好，有训练思路了么

**Comment by shanhaidexiamo** [comment]
> 你收索一下kaldi2 ，实测不错。
> […](#)

kaldi2能否走您这边的思路，转成onnx然后转其他平台支持的形式，适配不同平台呢，比如ios,安卓
