### ISSUE TITLE
有没有可以识别英文唤醒词的

### ISSUE THREAD

**Issue by asunnybaby** [chenyangMl/keyword-spot#10]
有没有可以识别英文唤醒词的模型。或者大佬可不可以教教我用英文唤醒词怎么finetune ，目前只有一万条1s 的唤醒词预料

**Comment by chenyangMl** [comment]
可以训练，
参考这个就行： https://k2-fsa.github.io/sherpa/onnx/kws/index.html 
数据的话还可以用TTS工具合成一部分，可以用这个： https://github.com/FunAudioLLM/CosyVoice
