### ISSUE TITLE
请问怎么用python  写推理代码呢, 使用ort的模型, 有参考的样例吗

### ISSUE THREAD

**Issue by yunqiushuiman** [chenyangMl/keyword-spot#2]
请问怎么用python  写推理代码呢, 使用ort的模型, 有参考的样例吗

**Comment by chenyangMl** [comment]
> 请问怎么用python 写推理代码呢, 使用ort的模型, 有参考的样例吗

python实现这里有，可以直接用的。 https://www.modelscope.cn/studios/thuduj12/KWS_Nihao_Xiaojing/summary
