### ISSUE TITLE
流式测试的结果

### ISSUE THREAD

**Issue by yangzhangok** [chenyangMl/keyword-spot#9]
作者您好！ 请问在使用麦克风接入时，正确的输出应该是怎样的，我的程序有如下警告，不知道是不是可以接入麦克风正常运行了？
`./stream_kws_main 0 40 80 keyword-spot-dstcn-maxpooling-wenwen/onnx/keyword-spot-dstcn-maxpooling-wenwen.ort
Kws Model Info:
	cache_dim: 256
	cache_len: 105
ALSA lib pcm_dsnoop.c:601:(snd_pcm_dsnoop_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib pcm_oss.c:397:(_snd_pcm_oss_open) Cannot open device /dev/dsp
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib confmisc.c:160:(snd_config_get_card) Invalid field card
ALSA lib pcm_usb_stream.c:482:(_snd_pcm_usb_stream_open) Invalid card 'card'
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
0 12
INFO (main():/home/zhangyang/code/keyword-spot/onnxruntime/bin/stream_kws_main.cc:115) === Now recording!! Please speak into the microphone. ===
`

应该如何接入麦克风呢？

**Comment by chenyangMl** [comment]
提示
“Now recording!! Please speak into the microphone”

表示接入了，开始录音了，你说对着麦克风说对应的唤醒词就可以了。
